namespace Loremaker.Text
{
    /// <summary>
    /// Represents one line of text that can be
    /// generated by a <see cref="TextTemplate"/>.
    /// </summary>
    public class TextTemplateLine
    {
        /// <summary>
        /// A line of text.
        /// </summary>
        public string Value { get; set; }

        /// <summary>
        /// A substring that must be present in 
        /// previous lines in order for a 
        /// <see cref="TextTemplate"/> to include this line.
        /// </summary>
        public string RequiredContext { get; set; }


        /// <summary>
        /// Creates a new <see cref="TextTemplateLine"/>.
        /// </summary>
        public TextTemplateLine(string value)
        {
            Value = value;
        }

        /// <summary>
        /// Creates a new <see cref="TextTemplateLine"/> with
        /// the specified context requirement.
        /// </summary>
        public TextTemplateLine(string value, string requiredContext)
        {
            Value = value;
            RequiredContext = requiredContext;
        }

        /// <summary>
        /// Returns true if this line has a context 
        /// requirement for <see cref="TextTemplate">
        /// TextTemplates</see> to use.
        /// </summary>
        public bool HasRequiredContext()
        {
            return RequiredContext != null;
        }

        public override string ToString()
        {
            return Value;
        }

    }
}
